project_id = "rndivcsonsojgelzewkb"

[functions.affiliate-redirect]
verify_jwt = false

[functions.loyalize-brands]
verify_jwt = true

[functions.loyalize-affiliate]  
verify_jwt = true

[functions.nctr-pricing]
verify_jwt = false

[functions.transaction-webhooks]
verify_jwt = false

[functions.purchase-webhook]
verify_jwt = false

[functions.treasury-withdrawal]
verify_jwt = true