project_id = "rndivcsonsojgelzewkb"

[functions.affiliate-redirect]
verify_jwt = false

[functions.affiliate-purchase-webhook]
verify_jwt = false

[functions.loyalize-brands]
verify_jwt = true

[functions.loyalize-affiliate]  
verify_jwt = true

[functions.nctr-pricing]
verify_jwt = true

[functions.transaction-webhooks] 
verify_jwt = false

[functions.purchase-webhook]
verify_jwt = false

[functions.treasury-withdrawal]
verify_jwt = true

[functions.nctr-price-feed]
verify_jwt = true

[functions.nctr-price-updater]
verify_jwt = true

[functions.loyalize-transaction-sync]
verify_jwt = false

[functions.manual-credit-purchase]
verify_jwt = true

[functions.process-purchase]
verify_jwt = false

[functions.impact-affiliate]
verify_jwt = true

[functions.mailchimp-integration]
verify_jwt = true

[functions.loyalize-integration]
verify_jwt = true

[functions.send-bulk-test-email]
verify_jwt = true

[functions.nctr-live-sync]
verify_jwt = true