project_id = "rndivcsonsojgelzewkb"

[functions.loyalize-brands]
verify_jwt = true

[functions.loyalize-affiliate]
verify_jwt = true

[functions.nctr-pricing]
verify_jwt = false

[functions.transaction-webhooks]
verify_jwt = false